### ISSUE TITLE
Add gz compression method

### ISSUE THREAD

**Issue by ruiztulio** [ruiztulio/backupws#43]
Sometime ins more important the speed of the generated backup than the size, ie when we need to create a testdb:
- Bakcup main instance
- Copy file to test server
- Restore it
- Deactivate it
- Remove or keep it untill next iteration

The the compression process can take about 10 minutes using bz2, but about the half using gz

**Comment by Codemaker83** [comment]
What if we just don't create any compressed file? When a testdb is created we can used the backup temporary dir immediately to restore the database.

**Comment by ruiztulio** [comment]
Because prod and test server are not the same thus they don't share the temp folder, and for some customers the dump and filestore is big enough to impact the copy time

**Comment by Codemaker83** [comment]
Ok.
